name: Deploy to Ubuntu Server

on:
  # push:
  #   branches: ["main"]
  pull_request:
    types: [closed]
    branches:
      - main  
  # merge:
  #   branches: ["main"] 
  # pull_request:
  #   branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Cache on node module
        run: echo "::set-env name=CACHE_KEY::$(runner.os)-node-${{ hashFiles('**/package-lock.json') }}"
        # run: echo " ${{ env.CACHE_KEY }}"
      - name: Restore cache
        uses: actions/cache@v2
        env:
         CACHE_RESTORE_KEYS: Linux-node-
        #  CACHE_KEY: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}
          # key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ env.CACHE_RESTORE_KEYS }}

#         uses: actions/cache@v2
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci    

      # - name: Build and test
      #   run: |
      #     npm install
      #     npm test

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          run: echo "$SSH_PRIVATE_KEY"
          username: ${{ secrets.SERVER_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          # ssh-key: ${{ secrets.SSH_PUBLIC_KEY }}
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          script: |
            cd /home/sprintdevs
            cd Safe-Courier-server-v1
            git pull 
            npm install
            # npm start
            pm2 restart index.js
