name: Deploy to Ubuntu Server

on:
  # push:
  #   branches: ["main"]
  pull_request:
    types: [closed]
    branches:
      - main  
  # pull_request:
  #   branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
      env:
        CACHE_RESTORE_KEYS: Linux-node-
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t michaelkasingye/server-courier:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push michaelkasingye/server-courier:latest


      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          run: echo "$SSH_PRIVATE_KEY"
          username: ${{ secrets.SERVER_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          script: |
            docker pull michaelkasingye/server-courier:latest
            docker run -d -p 9069:4000 michaelkasingye/server-courier:latest
            echo "End of Action"
